// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qllxfxmrfcvefaifuzua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsbHhmeG1yZmN2ZWZhaWZ1enVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTYxNjIsImV4cCI6MjA2OTA5MjE2Mn0.V2Js1Zm9BwqydEnkXgkCiJ7C2c2ebqFSpAMowJElaVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});